/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './index.html',
    './src/**/*.{js,jsx}',
    './components/**/*.{js,jsx}',
    './context/**/*.{js,jsx}',
  ],
  theme: {
    extend: {
      colors: {
        verde:      '#4A5C35',
        'verde-mid':'#5B7041',
        'verde-lt': '#697f4d',
        'verde-dk': '#2e3a20',
        surface:    '#f8f9fc',
        'surface-2':'#f1f3f8',
        'surface-3':'#e8ecf4',
        'surface-4':'#dde2ee',
        ink:        '#0f1923',
        'ink-2':    '#1a2736',
        'ink-3':    '#263545',
        gold:       '#C4975A',
        'gold-2':   '#d4a96a',
        'gold-lt':  '#e8c98a',
        'gold-dk':  '#a07840',
        muted:      '#7a8599',
        text:       '#1a2736',
        'text-2':   '#4a5568',
        'text-3':   '#8694a8',
      },
      fontFamily: {
        display: ['var(--font-display)', 'system-ui', 'sans-serif'],
        body:    ['var(--font-body)', 'system-ui', 'sans-serif'],
      },
      keyframes: {
        orbFloat:    { from:{ transform:'translate(0,0) scale(1)' }, to:{ transform:'translate(30px,-40px) scale(1.15)' } },
        pulseDot:    { '0%,100%':{ transform:'scale(1)', opacity:'1' }, '50%':{ transform:'scale(1.5)', opacity:'0.6' } },
        badgePulse:  { '0%,100%':{ opacity:'0.5', transform:'scale(1)' }, '50%':{ opacity:'1', transform:'scale(1.03)' } },
        floatCard:   { '0%,100%':{ transform:'translateY(0)' }, '50%':{ transform:'translateY(-8px)' } },
        scrollLine:  { '0%,100%':{ opacity:'0.3', transform:'scaleY(0.7)' }, '50%':{ opacity:'1', transform:'scaleY(1)' } },
        waRing:      { '0%':{ transform:'scale(1)', opacity:'0.6' }, '80%,100%':{ transform:'scale(1.3)', opacity:'0' } },

        shimmer:     { '0%':{ backgroundPosition:'-200% 0' }, '100%':{ backgroundPosition:'200% 0' } },
        glowPulse:   { '0%,100%':{ opacity:'0.3', transform:'scale(1)' }, '50%':{ opacity:'0.6', transform:'scale(1.08)' } },
        floatSlow:   { '0%,100%':{ transform:'translateY(0) rotate(0deg)' }, '50%':{ transform:'translateY(-12px) rotate(1deg)' } },
        slideUp:     { from:{ transform:'translateY(20px)', opacity:'0' }, to:{ transform:'translateY(0)', opacity:'1' } },
        slideIn:     { from:{ transform:'translateX(-20px)', opacity:'0' }, to:{ transform:'translateX(0)', opacity:'1' } },
        marquee:       { '0%': { transform: 'translateX(0%)' }, '100%': { transform: 'translateX(-100%)' } },
      },
      animation: {
        'orb-1':       'orbFloat 12s ease-in-out infinite alternate',
        'orb-2':       'orbFloat 15s 3s ease-in-out infinite alternate-reverse',
        'pulse-dot':   'pulseDot 2s ease infinite',
        'badge-ring':  'badgePulse 3s ease infinite',
        'float-card':  'floatCard 4s ease-in-out infinite',
        'scroll-ln':   'scrollLine 2s ease-in-out infinite',
        'wa-ring':     'waRing 2.5s ease infinite',

        'shimmer':     'shimmer 3s ease-in-out infinite',
        'glow-pulse':  'glowPulse 5s ease-in-out infinite',
        'float-slow':  'floatSlow 6s ease-in-out infinite',
        'slide-up':    'slideUp 0.6s ease-out forwards',
        'slide-in':    'slideIn 0.5s ease-out forwards',
        'marquee':        'marquee 55s linear infinite',
        'marquee-slow':   'marquee 90s linear infinite',
        'marquee-left':   'marqueeLeft 35s linear infinite',
        'marquee-right':  'marqueeRight 35s linear infinite',
      },
      transitionTimingFunction: {
        'expo-out': 'cubic-bezier(0.16, 1, 0.3, 1)',
      },
    },
  },
  plugins: [],
};
